apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
    project: snackbar
  namespace: snackbar
spec:
  type: ClusterIP
  selector:
    service: payment
    project: snackbar
  ports:
    - port: 80
      targetPort: 8080
