apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: my-app
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: yoonjeong/my-app:1.0
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: app-config
          mountPath: /etc/nginx/conf.d
        - name: tls
          mountPath: /etc/nginx/tls
      resources: {}
  volumes:
    - name: app-config
      configMap:
        name: nginx-config
    - name: tls
      secret:
        secretName: tls-config
