version: "3.9"

services:
  nginx:
    image: playground-nginx
    restart: unless-stopped
    ports:
      - 80:80

  nextjs:
    image: playground-app
    restart: unless-stopped
    ports:
      - 3000:3000
