version: "3.9"

services:
  nginx:
    build: ./nginx
    image: playground-nginx
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - nextjs-playground
  nextjs:
    build: .
    image: playground-app
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - nextjs-playground

networks:
  nextjs-playground: {}
