apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: delivery
  labels:
    project: snackbar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delivery-app
  template:
    metadata:
      name: delivery
      namespace: delivery
      labels:
        app: delivery-app
        project: snackbar
    spec:
      containers:
        - name: delivery-web
          image: dlgustn555/delivery:5.0.1
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: DELIVERY_HTTP_PORT
                  name: port-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: payment
  labels:
    project: snackbar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      name: payment-app
      namespace: payment
      labels:
        app: payment-app
        project: snackbar
    spec:
      containers:
        - name: payment-web
          image: dlgustn555/payment:5.0.1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_HTTP_PORT
                  name: port-config
          resources: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: order
  labels:
    project: snackbar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      name: order
      namespace: order
      labels:
        app: order-app
        project: snackbar
    spec:
      containers:
        - name: order-web
          image: dlgustn555/order:5.0.3
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: ORDER_HTTP_PORT
                  name: port-config
          resources: {}
