apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snackbar
  namespace: order
  labels:
    project: snackbar
spec:
  defaultBackend:
    service:
      name: order
      port:
        number: 80
  # rules:
