apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    service: order
    project: snackbar
  namespace: snackbar
spec:
  type: NodePort
  selector:
    service: order
  ports:
    - port: 80
      targetPort: 8080
