apiVersion: v1
kind: Pod
metadata:
  name: unhealthy
  labels:
    app: myapp
spec:
  containers:
    - name: unhealthy
      image: hoonjeong/unhealthy-app:1.0
      ports:
        - containerPort: 8080
      readinessProbe:
        exec: # 컨테이너 안에서 실행할 command 명령어를 작성
          command:
            - ls
            - /var/ready
        initialDelaySeconds: 60
        successThreshold: 1
        failureThreshold: 1
        periodSeconds: 5
        timeoutSeconds: 10
      resources: {}
