version: "3.9"
services:
  grafana:
    image: grafana/grafana:8.2.6
    restart: unless-stopped
    ports:
      - 5000:3000
    # environment:
    #   - GF_INSTALL_PLUGINS=value
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana-data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "5"

volumes:
  grafana-data: {}
