apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    service: delivery
    project: snackbar
  namespace: hyunsu
spec:
  type: ClusterIP
  selector:
    service: delivery
  ports:
    - port: 80
      targetPort: 8080
