apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      service: payment
  template:
    metadata:
      name: payment
      labels:
        service: payment
    spec:
      containers:
        - name: payment
          image: dlgustn555/payment:1.0.0
          ports:
            - containerPort: 8080
          resources: {}
