apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: my-app-pod
  template:
    metadata:
      labels:
        pod: my-app-pod
    spec:
      containers:
        - name: c-my-app
          image: my-app:1.0.0
          ports:
            - containerPort: 8080
          resources: {}
