apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: hello-pod
  labels:
    group: greeting
    version: v1
spec:
  containers:
    - name: hello-app
      image: dlgustn555/hello
      ports:
        - containerPort: 8080
      resources: {}
