apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    service: order
    project: snackbar
  namespace: lee
spec:
  replicas: 3
  selector:
    matchLabels:
      service: order
  template:
    metadata:
      labels:
        service: order
        project: snackbar
      namespace: lee
    spec:
      containers:
        - name: order
          image: dlgustn555/order:1.0.0
          ports:
            - containerPort: 8080
          resources: {}
