apiVersion: v1
kind: Pod
metadata:
  name: hello-app
spec:
  containers:
    - name: hello-app
      image: devchloe/hello-app:1.0
      ports:
        - containerPort: 3100 # 해당 컨테이너의 포트는 3100 포트이다.
      resources: {}
      env:
        - name: STUDENT_NAME
          value: 홍길동
        - name: GREETING
          value: 쿠버네티스 입문강의에 오신것을 환경합니다. $(STUDENT_NAME) 님!
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
