apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
    project: snackbar
  namespace: lee
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: payment
  type: ClusterIP
