version: "3.9"
services:
  jenkins:
    restart: unless-stopped
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins:/var/jenkins_home
    user: root
volumes:
  jenkins: {}
