pipeline {
    agent any
    stages {
        stage('Pull Codes from Github') {
            steps {
                checkout scm
            }
        }

        stage('NextJs-App Dockerfile Build') {
            steps {
                sh 'docker build -t dlgustn555/nextjs-playground .'
            }
        }

        stage('Docker Hub Login') {
        steps {
            withCredentials([string(credentialsId: 'docker-hub-password', variable: 'DOCKER_HUB_PASSWORD')]) {
                sh "echo '${DOCKER_HUB_PASSWORD}' | docker login -u dlgustn555 --password-stdin"
            }
        }
    }
        stage('NextJs-App Docker Image Push') {
            steps {
                sh 'docker push dlgustn555/nextjs-playground'
            }
        }

        // stage('DELETE NextJs-App Docker Image ') {
        //     steps {
        //         sh 'docker rmi dlgustn555/nextjs-playground'
        //     }
        // }

        stage('Deploy NextJs-App to Web Server') {
            steps {
                sh 'ssh dlgustn555@192.168.56.101 "docker run -d -p 3000:3000 dlgustn555/nextjs-playground"'
            }
        }
    }
}