pipeline {
    agent any
    stages {
        stage('Pull Codes from Github') {
            steps {
                checkout scm
            }
        }

        stage('NextJs-App Dockerfile Build') {
            steps {
                sh 'docker build -t dlgustn555/nextjs-playground .'
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-id', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('NextJs-App Docker Image Push') {
            steps {
                sh 'docker push dlgustn555/nextjs-playground'
            }
        }

        // stage('DELETE NextJs-App Docker Image ') {
        //     steps {
        //         sh 'docker rmi dlgustn555/nextjs-playground'
        //     }
        // }

        stage('Deploy NextJs-App to Web Server') {
            steps {
                sh 'ssh dlgustn555@192.168.56.101 "docker run -d -p 3000:3000 dlgustn555/nextjs-playground"'
            }
        }
    }
}
