apiVersion: v1
kind: Pod
metadata:
  name: ch03-app-pod
spec:
  containers:
    - name: c-ch03-app-pod
      image: ch03-app
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3300
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      resources: {}
