apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: payment
spec:
  type: LoadBalancer
  selector:
    app: payment-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  namespace: payment
  labels:
    app: payment-app
spec:
  containers:
    - name: payment-app
      image: dlgustn555/payment:5.0.0
      ports:
        - containerPort: 8080
      resources: {}
