apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: nextjs-app
          image: dlgustn555/{{ .Values.name }}:{{ .Values.IMAGE_TAG }}
          ports:
            - containerPort: 3000
