apiVersion: apps/v1
kind: Deployment
metadata:
  name: "deploy-{{ .Values.name }}"
  namespace: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  replicas: "{{ .Values.replicaCount }}"
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      name: "pod-{{ .Values.name }}"
      namespace: "{{ .Values.name }}"
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - name: nextJs-app
          image: dlgustn555/nextjs-playground:{{ .Values.app.tag }}
          ports:
            - containerPort: 3000
