apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  containers:
    - name: hello-app
      image: yoonjeong/hello-app:1.0
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: greeting-config
      env:
        - name: GREETING
          value: $(STUDENT_NAME) $(MESSAGE)
      resources: {}
