apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: delivery
spec:
  type: LoadBalancer
  selector:
    app: delivery-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: delivery
  namespace: delivery
  labels:
    app: delivery-app
spec:
  containers:
    - name: delivery-app
      image: dlgustn555/delivery:5.0.1
      ports:
        - containerPort: 8080
      resources: {}
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: ORDER_HTTP_PORT
              name: port-config
