apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: order
spec:
  type: LoadBalancer
  selector:
    app: order-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: order
  namespace: order
  labels:
    app: order-app
spec:
  containers:
    - name: order-app
      image: dlgustn555/order:5.0.2
      ports:
        - containerPort: 8080
      resources: {}
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: ORDER_HTTP_PORT
              name: port-config
