apiVersion: v1
kind: Service
metadata:
  name: ch00-LoadBalancer-service
  labels:
    project: ch00
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ch00-pod
