apiVersion: v1
kind: Pod
metadata:
  name: ch00-pod
  labels:
    project: ch00
spec:
  containers:
    - name: order
      image: dlgustn555/order:4.0.1
      ports:
        - containerPort: 8080
      resources: {}
